Fix Min/Max macro clash in symmetrica on Windows
Fixes
```
"cl.exe" "-Isrc\sage\libs\symmetrica\symmetrica.cp311-win_amd64.pyd.p" "-Isrc\sage\libs\symmetrica" "-I..\src\sage\libs\symmetrica" "-IC:\Users\Tobia\.conda\envs\sage-dev\Lib\site-packages\cysignals" "-IC:\Users\Tobia\.conda\envs\sage-dev\Include" "-IC:/Users/Tobia/.conda/envs/sage-dev/Library/include" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c17" "/O2" "/Gw" "-DMS_WIN64=" "/Fdsrc\sage\libs\symmetrica\symmetrica.cp311-win_amd64.pyd.p\meson-generated_src_sage_libs_symmetrica_symmetrica.pyx.c.pdb" /Fosrc/sage/libs/symmetrica/symmetrica.cp311-win_amd64.pyd.p/meson-generated_src_sage_libs_symmetrica_symmetrica.pyx.c.obj "/c" src/sage/libs/symmetrica/symmetrica.cp311-win_amd64.pyd.p/src/sage/libs/symmetrica/symmetrica.pyx.c
C:/Users/Tobia/.conda/envs/sage-dev/Library/include\symmetrica/def.h(1898): error C4003: not enough arguments for function-like macro invocation 'min'
C:/Users/Tobia/.conda/envs/sage-dev/Library/include\symmetrica/def.h(1898): error C2059: syntax error: '<parameter-list>'
src/sage/libs/symmetrica/symmetrica.cp311-win_amd64.pyd.p/src/sage/libs/symmetrica/symmetrica.pyx.c(15055): warning C4113: 'INT (__cdecl *)()' differs in parameter lists from 'INT (__cdecl *)(void)'
ninja: build stopped: subcommand failed.
```