Fix type narrowing conversion exception on Windows
Fixes
```
"cl.exe" "-Isrc\sage\graphs\base\boost_graph.cp311-win_amd64.pyd.p" "-Isrc\sage\graphs\base" "-I..\src\sage\graphs\base" "-Isrc\sage\cpython" "-I..\src\sage\cpython" "-Isrc\sage\data_structures" "-I..\src\sage\data_structures" "-Isrc\sage\rings" "-I..\src\sage\rings" "-IC:\Users\Tobia\.conda\envs\sage-dev\Lib\site-packages\cysignals" "-IC:\Users\Tobia\.conda\envs\sage-dev\Include" "-IC:/Users/Tobia/.conda/envs/sage-dev/Library/include" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/Zc:__cplusplus" "/W2" "/EHsc" "/std:c++17" "/permissive-" "/O2" "/Gw" "-DMS_WIN64=" "-DBOOST_NO_ARGUMENT_DEPENDENT_LOOKUP" "/Fdsrc\sage\graphs\base\boost_graph.cp311-win_amd64.pyd.p\meson-generated_src_sage_graphs_base_boost_graph.pyx.cpp.pdb" /Fosrc/sage/graphs/base/boost_graph.cp311-win_amd64.pyd.p/meson-generated_src_sage_graphs_base_boost_graph.pyx.cpp.obj "/c" src/sage/graphs/base/boost_graph.cp311-win_amd64.pyd.p/src/sage/graphs/base/boost_graph.pyx.cpp
..\src\sage\graphs\base\boost_interface.cpp(122): error C2398: Element '1': conversion from 'unsigned __int64' to 'const _Ty1 &' requires a narrowing conversion
        with
        [
            _Ty1=v_index
        ]
..\src\sage\graphs\base\boost_interface.cpp(122): note: the template instantiation context (the oldest one first) is
src/sage/graphs/base/boost_graph.cp311-win_amd64.pyd.p/src/sage/graphs/base/boost_graph.pyx.cpp(7797): note: see reference to class template instantiation 'BoostGraph<boost::vecS,boost::vecS,boost::directedS,boost::vecS,__pyx_t_4sage_6graphs_4base_11boost_graph_EdgeWeight>' being compiled
..\src\sage\graphs\base\boost_interface.cpp(115): note: while compiling class template member function 'std::vector<std::pair<v_index,std::pair<v_index,double>>,std::allocator<std::pair<v_index,std::pair<v_index,double>>>> BoostGraph<boost::vecS,boost::vecS,boost::directedS,boost::vecS,__pyx_t_4sage_6graphs_4base_11boost_graph_EdgeWeight>::edge_list(void)'
src/sage/graphs/base/boost_graph.cp311-win_amd64.pyd.p/src/sage/graphs/base/boost_graph.pyx.cpp(17466): note: see the first reference to 'BoostGraph<boost::vecS,boost::vecS,boost::directedS,boost::vecS,__pyx_t_4sage_6graphs_4base_11boost_graph_EdgeWeight>::edge_list' in '__pyx_fuse_2__pyx_f_4sage_6graphs_4base_11boost_graph_get_predecessors'
```
when compiling with MSVC.