`CircuitsMatroid`: check for empty dict before min
This was already working as intented (confusingly), probably due to some Cython optimization which avoided the min on an empty dict.
I added the check for clarity and robustness.

For example, this calls min on an empty dict:
```python
sage: from sage.matroids.circuits_matroid import CircuitsMatroid
sage: M = matroids.Uniform(5, 5)
sage: CM = CircuitsMatroid(M)
sage: CM.dependent_sets(2)
SetSystem of 0 sets over 5 elements
```

The addition of a `print(min(self._k_C))` makes the issue clear, as it raises:
```
ValueError: min() iterable argument is empty
```