build/pkgs/contourpy: Ignore array and string bounds checking
contourpy SPKG fails to build on conda environment with GCC 12.4.0
due to `-Werror=array-bounds` flag emitted when compiling pybind
wrapper (wrap.cpp):

```
[spkg-install] /home/bagas/miniconda3/envs/sagemath/bin/x86_64-conda-linux-gnu-c++ -Isrc/_contourpy.cpython-311-x86_64-linux-gnu.so.p -Isrc -I../src -I/home/bagas/miniconda3/envs/sagemath/include/python3.11 -I/home/bagas/miniconda3/envs/sagemath/lib/python3.11/site-packages/pybind11/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++17 -O3 -O2 -march=haswell -mtune=haswell -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fPIC -DCONTOURPY_VERSION=1.1.1 -MD -MQ src/_contourpy.cpython-311-x86_64-linux-gnu.so.p/wrap.cpp.o -MF src/_contourpy.cpython-311-x86_64-linux-gnu.so.p/wrap.cpp.o.d -o src/_contourpy.cpython-311-x86_64-linux-gnu.so.p/wrap.cpp.o -c ../src/wrap.cpp
<snipped>...
[spkg-install] /home/bagas/miniconda3/envs/sagemath/lib/gcc/x86_64-conda-linux-gnu/12.4.0/include/c++/bits/stl_algobase.h:434:30: error: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' forming offset 8 is out of the bounds [0, 8] of object '<anonymous>' with type 'pybind11::detail::type_info* const [1]' [-Werror=array-bounds]
[spkg-install]   434 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
[spkg-install]       |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[spkg-install] /home/bagas/miniconda3/envs/sagemath/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h: In member function 'void pybind11::detail::generic_type::initialize(const pybind11::detail::type_record&)':
[spkg-install] /home/bagas/miniconda3/envs/sagemath/lib/python3.11/site-packages/pybind11/include/pybind11/pybind11.h:1343:71: note: '<anonymous>' declared here
[spkg-install]  1343 |         internals.registered_types_py[(PyTypeObject *) m_ptr] = {tinfo};
[spkg-install]       |                                                                       ^
[spkg-install] cc1plus: all warnings being treated as errors
```

Ignore the flag (`-Wno-array-bounds`) plus string bounds checking
(`-Wno-stringop-overread`) to make contourpy builds again.